apiVersion: 1
contactPoints:
  - orgId: 1
    name: perfana
    is_default: true
    receivers:
      - uid: perfana
        type: webhook
        settings:
          httpMethod: POST
          url: ${PERFANA_ALERTS_WEBHOOK_URL}
          username: perfana
          password: perfana