global: {}

receivers:
- name: default-receiver
  webhook_configs:
  - url: 'http://perfana:3000/api/prometheus-alerts'
    send_resolved: false
    http_config:
      basic_auth:
        username: admin@perfana.io
        password: perfana

route:
  receiver: default-receiver
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 3h
