apiVersion: 1
datasources:
  - name: perfana-JSON-API
    type: marcusolsson-json-datasource
    url: http://perfana-fe:3000
    access: proxy
    uid: perfana-json-api
    basicAuth: true
    editable: false
    basicAuthUser: admin@perfana.io
    secureJsonData:
      basicAuthPassword: perfana
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    uid: prometheus
    editable: true
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    uid: loki
    editable: true
    basicAuth: true
  - name: influxDb-gatling
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    uid: influxdb-gatling
    editable: true
    database: gatling3
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: perfana
  - name: influxDb-jmeter
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    uid: influxdb-jmeter
    editable: true
    database: jmeter
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: perfana
  - name: influxDb-jfr
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    uid: influxdb-jfr
    editable: true
    database: jfr
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: perfana
  - name: influxDb-k6
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    uid: influxdb-k6
    editable: true
    database: k6
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: perfana
  - name: influxDb-locust
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    uid: influxdb-locust
    editable: true
    database: locust
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: perfana
  - name: influxDb-neoload
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    uid: influxdb-neoload
    editable: true
    database: neoload
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: perfana
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
        tags: []
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: prometheus
        hide: false
