{
 "title": "Span metrics",
 "tags": [
  "perfana",
  "spanmetrics",
  "perfana-template"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "label": "System under test",
    "query": "SELECT DISTINCT system_under_test FROM requests_raw ORDER BY 1"
   },
   {
    "name": "test_environment",
    "label": "Test environment",
    "query": "SELECT DISTINCT test_environment FROM requests_raw WHERE system_under_test = '$system_under_test' ORDER BY 1"
   },
   {
    "name": "scenarioName",
    "label": "Scenario",
    "query": "SELECT DISTINCT scenario_name FROM requests_raw WHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' ORDER BY 1"
   },
   {
    "name": "transaction",
    "label": "Transaction",
    "query": "SELECT DISTINCT transaction_name FROM requests_raw WHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenarioName) ORDER BY 1"
   },
   {
    "name": "requestName",
    "label": "Request name",
    "query": "SELECT DISTINCT scenario_name || '|' || transaction_name || '|' || sampler_name FROM requests_raw WHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenarioName) AND transaction_name IN ($transaction) ORDER BY 1"
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_bucket,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "95th percentile span durations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, avg by(le,span_name,service) (increase(traces_spanmetrics_latency_bucket{perfana_request_name=\"$requestName\", service=~\"$service\"}[1m])))",
     "legendFormat": "{{service}} | {{span_name}}"
    }
   ]
  },
  {
   "title": "Spans / sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service, span_name) (increase(traces_spanmetrics_calls_total{perfana_request_name=\"$requestName\", service=~\"$service\"}[1m])) / 60",
     "legendFormat": "{{service}} | {{span_name}}"
    }
   ]
  },
  {
   "title": "Span duration percentiles",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, max by(le,span_name,service) (increase(traces_spanmetrics_latency_bucket{perfana_request_name=\"$requestName\", service=~\"$service\"}[1m])))",
     "legendFormat": "{{service}} | {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le,span_name,service) (increase(traces_spanmetrics_latency_bucket{perfana_request_name=\"$requestName\", service=~\"$service\"}[1m])))",
     "legendFormat": "{{service}} | {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, max by(le,span_name,service) (increase(traces_spanmetrics_latency_bucket{perfana_request_name=\"$requestName\", service=~\"$service\"}[1m])))",
     "legendFormat": "{{service}} | {{span_name}}"
    }
   ]
  },
  {
   "title": "Span count",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service, span_name) (increase(traces_spanmetrics_calls_total{perfana_request_name=\"$requestName\", service=~\"$service\"}[$__range]))",
     "legendFormat": "{{service}} | {{span_name}}"
    }
   ]
  }
 ]
}