{
 "title": "Request analysis TimescaleDB",
 "time": { "from": "2025-12-24T10:02:39.465Z", "to": "2025-12-24T10:11:22.541Z" },
 "templating": {
  "list": [
   { "name": "cagg_suffix", "label": "CAGG resolution", "query": "5s,1m,5m" },
   {
    "name": "system_under_test",
    "query": "SELECT DISTINCT s.name\nFROM systems_under_test s\nJOIN test_runs tr ON tr.system_under_test_id = s.id\nORDER BY 1"
   },
   {
    "name": "test_environment",
    "query": "SELECT DISTINCT tr.test_environment\nFROM test_runs tr\nJOIN systems_under_test s ON s.id = tr.system_under_test_id\nWHERE s.name = '$system_under_test'\nORDER BY 1"
   },
   {
    "name": "scenario_name",
    "query": "SELECT DISTINCT scenario_name\nFROM requests_raw\nWHERE system_under_test = '$system_under_test'\n  AND test_environment = '$test_environment'\n  AND $__timeFilter(time)\nORDER BY 1"
   },
   {
    "name": "sampler_name",
    "query": "SELECT DISTINCT sampler_name\nFROM requests_raw\nWHERE system_under_test = '$system_under_test'\n  AND test_environment = '$test_environment'\n  AND scenario_name IN ($scenario_name)\n  AND $__timeFilter(time)\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Min Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms " } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT last(\"currentActiveThreads\") FROM \"virtualUsers\" WHERE time > ${__from}ms and time > now() - 5m GROUP BY (nodeName)",
     "rawSql": "SELECT\n  min(response_time) as min\nFROM requests_raw\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND success is TRUE \n  AND $__timeFilter(time)\n",
     "tags": [
      { "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms " } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT last(\"currentActiveThreads\") FROM \"virtualUsers\" WHERE time > ${__from}ms and time > now() - 5m GROUP BY (nodeName)",
     "rawSql": "SELECT\n  avg(response_time) as avg\nFROM requests_raw\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND success is TRUE \n  AND $__timeFilter(time)\n",
     "tags": [
      { "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "P95 Connect time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms " } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT last(\"currentActiveThreads\") FROM \"virtualUsers\" WHERE time > ${__from}ms and time > now() - 5m GROUP BY (nodeName)",
     "rawSql": "SELECT\n  percentile_cont(0.95) WITHIN GROUP (ORDER BY response_time) AS p95\nFROM requests_raw\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND success IS TRUE\n  AND $__timeFilter(time);\n",
     "tags": [
      { "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms " } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT last(\"currentActiveThreads\") FROM \"virtualUsers\" WHERE time > ${__from}ms and time > now() - 5m GROUP BY (nodeName)",
     "rawSql": "SELECT\n  max(response_time) as max\nFROM requests_raw\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND success is TRUE \n  AND $__timeFilter(time)\n",
     "tags": [
      { "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Throughput",
     "measurement": "requestsRaw",
     "query": "SELECT sum(\"sum\")  / 10 * 8 FROM \"requestsAggregated_10s\" WHERE time > now() - 1m and time > ${__from}ms GROUP BY time(10s), \"requestName\" fill(null)",
     "rawSql": "SELECT\n  avg(response_size) as avg\nFROM requests_raw\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND success is TRUE \n  AND $__timeFilter(time)\n",
     "tags": [
      { "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT \"responseCode\" FROM \"default\".\"requestsError\" WHERE (\"samplerName\" =~ /^$URL$/) AND $timeFilter",
     "rawSql": "SELECT\n  sum(n) as count\nFROM requests_raw_5m\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND $__timeFilter(bucket)\n",
     "tags": [
      { "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "requestsError",
     "query": "SELECT \"responseCode\" FROM \"default\".\"requestsError\" WHERE (\"samplerName\" =~ /^$URL$/) AND $timeFilter",
     "rawSql": "SELECT\n  sum(n_err) as count\nFROM requests_raw_5m\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND $__timeFilter(bucket)\n",
     "tags": [
      { "key": "samplerName", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "$transaction Response Times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  CASE WHEN success THEN response_time END AS OK,\n  CASE WHEN NOT success THEN response_time END AS Error\nFROM requests_raw\nWHERE system_under_test = '$system_under_test' \n  AND test_environment = '$test_environment'  \n  AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND $__timeFilter(time)\nORDER BY 1\nLIMIT 235139"
    },
    {
     "rawSql": "SELECT\ntime_bucket('$__interval', bucket) AS time,\n  sum(avg_rt * n) / NULLIF(sum(n), 0) as avg\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment'\n  AND sampler_name = '$sampler_name'\n  AND $__timeFilter(bucket)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_samplerName",
     "groupBy": [
      { "params": [ "${granularity}s" ], "type": "time" },
      { "params": [ "samplerName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT (count(\"responseCode\")  / $granularity) as value FROM \"requestsRaw\" WHERE (\"success\" = 'true') AND \"samplerName\" =~ /${URL}/ AND $timeFilter GROUP BY time(${granularity}s), \"samplerName\" fill(none)",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sum(n)::float / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) as total,\n  sum(n_err)::float / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) AS Error\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n  AND sampler_name = '$sampler_name'\n  AND $__timeFilter(bucket)\nGROUP BY 1\nORDER BY 1;",
     "tags": [
      { "key": "success::tag", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentile",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH ordered AS (\n  SELECT response_time,\n         ROW_NUMBER() OVER (ORDER BY response_time) AS rn,\n         COUNT(*) OVER () AS total\n  FROM requests_raw\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n    AND sampler_name = '$sampler_name'\n    AND success IS TRUE\n    AND $__timeFilter(time)\n)\nSELECT\n  ROUND(100.0 * rn / total, 2) AS percentile,\n  response_time AS value\nFROM ordered\nORDER BY percentile;\n"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Mean Response Size",
     "groupBy": [
      { "params": [ "${granularity}s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sampler_name,\n  ROUND(sum(avg_response_size * n) / NULLIF(sum(n), 0))\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND\n      sampler_name='$sampler_name' AND\n      $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;",
     "tags": [
      { "key": "samplerName", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "success::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "measurement": "requestsError",
     "query": "SELECT time, randomId, responseTime, responseCode, samplerName, url, transactionName, nodeName, responseMessage FROM \"requestsError\" WHERE \"samplerName\" = ${URL:singlequote}  AND $timeFilter order by time desc limit 100",
     "rawSql": "SELECT\n  time,\n  sampler_name,\n  transaction_name,\n  response_time,\n  node_name,\n  random_id,\n  url,\n  response_code,\n  response_message\nFROM requests_error\nWHERE system_under_test = '$system_under_test' and test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND\n      $__timeFilter(time) AND \n      sampler_name='$sampler_name'\nORDER BY 1 DESC\nLIMIT 100;",
     "tags": [
      { "key": "samplerName::tag", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  }
 ]
}