{
 "title": "JVM memory management G1GC",
 "tags": [
  "JVM",
  "G1GC",
  "perfana",
  "perfana-template"
 ],
 "time": { "from": "2023-07-20T11:02:32.141Z", "to": "2023-07-20T14:16:12.098Z" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, system_under_test)"
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{system_under_test=\"$system_under_test\"}, test_environment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average JVM Heap % used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\"}) / sum(jvm_memory_committed_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\"})",
     "legendFormat": "JVM Heap % used"
    }
   ]
  },
  {
   "title": "Average JVM Non-Heap % used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\"}) / sum(jvm_memory_max_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\"}) ",
     "legendFormat": "JVM Non-Heap % used"
    }
   ]
  },
  {
   "title": "Average JVM Total % used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"})/ sum(jvm_memory_max_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) ",
     "legendFormat": "JVM Total % used"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections end of minor GC by cause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_pause_seconds_count{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of minor GC\"}[1m])) by(cause)",
     "legendFormat": "{{pod}} {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Average Pause Durations end of minor GC by cause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_pause_seconds_sum{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of minor GC\"}[1m])/rate(jvm_gc_pause_seconds_count{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of minor GC\"}[1m])) by(cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Maximum Pause Durations end of minor GC by cause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(jvm_gc_pause_seconds_max{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of minor GC\"}) by(cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Young generation memory pool increase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_memory_allocated_bytes_total{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m]))",
     "legendFormat": "allocated"
    }
   ]
  },
  {
   "title": "Collections end of major GC by cause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_pause_seconds_count{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of major GC\"}[1m])) by(cause)",
     "legendFormat": "{{pod}} {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Average Pause Durations end of major GC by cause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_pause_seconds_sum{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of major GC\"}[1m])/rate(jvm_gc_pause_seconds_count{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of major GC\"}[1m])) by(cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Maximum Pause Durations end of major GC by cause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(jvm_gc_pause_seconds_max{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", action=\"end of major GC\"}) by(cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Old generation memory pool increase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_memory_promoted_bytes_total{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m]))",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Eden Space in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\", id=~\".*Eden Space\"})",
     "legendFormat": "Eden Space in use"
    }
   ]
  },
  {
   "title": "Average Survivor Space in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\", id=~\".*Survivor Space\"})",
     "legendFormat": "Survivor Space in use"
    }
   ]
  },
  {
   "title": "Average Tenured Gen in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\", id=~\".*Tenured Gen\"})",
     "legendFormat": "Tenured Gen in use"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CodeHeap 'non-nmethods' % in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"CodeHeap 'non-nmethods'\"} / jvm_memory_max_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"CodeHeap 'non-nmethods'\"} )",
     "legendFormat": "CodeHeap 'non-nmethods' % in use"
    }
   ]
  },
  {
   "title": "Average CodeHeap 'non-profiled nmethods' % in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"CodeHeap 'non-profiled nmethods'\"} / jvm_memory_max_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"CodeHeap 'non-profiled nmethods'\"} )",
     "legendFormat": "CodeHeap 'non-profiled nmethods' % in use"
    }
   ]
  },
  {
   "title": "Average CodeHeap 'profiled nmethods' % in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"CodeHeap 'profiled nmethods'\"} / jvm_memory_max_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"CodeHeap 'profiled nmethods'\"} )",
     "legendFormat": "CodeHeap 'profiled nmethods' % in use"
    }
   ]
  },
  {
   "title": "Average Compressed Class Space % in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"Compressed Class Space\"} / jvm_memory_max_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\", id=\"Compressed Class Space\"} )",
     "legendFormat": "Compressed Class Space % in use"
    }
   ]
  }
 ]
}