{
 "title": "JMeter",
 "tags": [
  "perfana",
  "perfana-template",
  "JMeter",
  "perfana-performance-test-tool"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": "show tag values  from requests with key=\"systemUnderTest\""
   },
   {
    "name": "test_environment",
    "query": "show tag values from requests with key=\"testEnvironment\" where \"systemUnderTest\" =~ /$system_under_test/"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean overall response times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "mean response time",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "requests",
     "query": "SELECT mean(\"duration\") FROM \"30d\".\"requests\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "allThreads",
     "query": "SELECT mean(\"allThreads\") FROM \"30d\".\"allThreads\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "allThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Total passed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Requests per second",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Total failed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'false') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Passed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_label",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($interval), \"label\"::tag",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Failed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_label",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'false') AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Error messages count",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "$tag_name $measurement ",
     "groupBy": [
      { "params": [ "label::tag" ], "type": "tag" },
      { "params": [ "responseCode::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\") FROM \"30d\".\"requests\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'false') AND $timeFilter GROUP BY \"name\", \"errorMessage\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": " status: $tag_responseCode $tag_label",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" },
      { "params": [ "responseCode::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'false') AND $timeFilter GROUP BY time($interval), \"name\", \"errorMessage\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Number of requests OK vs KO",
   "type": "table",
   "description": "perfana-response-times",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_name $tag_result",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  AS \"OK\"  FROM \"30d\".\"requests\" WHERE (\"success\" = 'true' AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter GROUP BY \"label\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "alias": "$tag_name $tag_result",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  AS \"KO\"  FROM \"30d\".\"requests\" WHERE ( \"success\" = 'false' AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ ) AND $timeFilter GROUP BY \"label\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentage failed requests",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Cumulative % failed",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "errorMessage" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT (CUMULATIVE_SUM(mean(\"failed\"))  /  CUMULATIVE_SUM(mean(\"total\")) ) * 100 FROM \"30d\".\"jmeter-throughput\"  WHERE ( \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter group by time(10s) fill(0)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Performance overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response times",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT mean(\"duration\"), min(\"duration\"), percentile(\"duration\", 50), percentile(\"duration\", 90), percentile(\"duration\", 99), max(\"duration\"), count(\"duration\") FROM \"30d\".\"requests\" WHERE ( \"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"success\" = 'true') AND $timeFilter GROUP BY \"label\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "success::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  { "title": "Performance over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Average Response times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_label",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "jmeter-percentiles",
     "query": "SELECT mean(\"cq_mean_response_time\") FROM \"30d\".\"jmeter-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($__interval), \"label\"::tag",
     "select": [
      [
       { "params": [ "cq_mean_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times maximum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_label",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "jmeter-percentiles",
     "query": "SELECT mean(\"cq_max_response_time\") FROM \"30d\".\"jmeter-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\"::tag = 'true') AND $timeFilter GROUP BY time($__interval), \"label\"::tag",
     "select": [
      [
       { "params": [ "cq_max_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times stdDev",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_label",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "jmeter-percentiles",
     "query": "SELECT mean(\"cq_stddev_response_time\") FROM \"30d\".\"jmeter-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($__interval), \"label\"::tag",
     "select": [
      [
       { "params": [ "cq_stddev_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_label",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "jmeter-percentiles",
     "query": "SELECT mean(\"cq_50pct_response_time\") FROM \"30d\".\"jmeter-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($__interval), \"label\"::tag",
     "select": [
      [
       { "params": [ "cq_50pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_label",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "jmeter-percentiles",
     "query": "SELECT mean(\"cq_90pct_response_time\") FROM \"30d\".\"jmeter-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($__interval), \"label\"::tag",
     "select": [
      [
       { "params": [ "cq_90pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_label",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" }
     ],
     "measurement": "jmeter-percentiles",
     "query": "SELECT mean(\"cq_99pct_response_time\") FROM \"30d\".\"jmeter-percentiles\" WHERE ( \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_99pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
     ]
    }
   ]
  }
 ]
}