{
 "title": "K6 http",
 "tags": [
  "perfana",
  "perfana-template",
  "k6",
  "perfana-performance-test-tool"
 ],
 "time": { "from": "2023-12-01T10:54:31.964Z", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": "show tag values  from http_req_duration with key=\"systemUnderTest\""
   },
   {
    "name": "test_environment",
    "query": "show tag values from http_req_duration with key=\"testEnvironment\" where \"systemUnderTest\" =~ /$system_under_test/"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total passed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Total passed request / second",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"http_req_duration\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Total failed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Total failed requests / second",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"http_req_duration\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'false') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Passed requests per second",
   "type": "timeseries",
   "description": "perfana-request-names",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"http_req_duration\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($interval), \"name\"::tag",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Failed requests per second",
   "type": "timeseries",
   "description": "perfana-request-names",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"http_req_duration\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'false') AND $timeFilter GROUP BY time($interval), \"name\"::tag",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "alias": "$tag_name $tag_result",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"duration\") FROM \"30d\".\"http_req_duration\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "$tag_name $tag_result",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"percentiles99\") FROM \"gatling2\" WHERE  \"simulation\" =~ /^$simulation$/ AND \"result\" = 'ok' AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "status::tag", "operator": "!=", "value": "0" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative percentage failed requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "% failed",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "errorMessage" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT (CUMULATIVE_SUM(mean(\"failed\"))  /  CUMULATIVE_SUM(mean(\"total\")) ) * 100 FROM \"30d\".\"k6-throughput\"  WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter group by time(10s) fill(0)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" }
     ]
    }
   ]
  },
  {
   "title": "Error messages count",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "$tag_name $measurement ",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "error::tag" ], "type": "tag" },
      { "params": [ "status::tag" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"duration\") FROM \"30d\".\"http_req_duration\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'false') AND $timeFilter GROUP BY \"name\", \"error\"::tag, \"status\"::tag",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_name | http status code $tag_status",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "status::tag" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"http_req_duration\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'false') AND $timeFilter GROUP BY time($interval), \"name\", \"status\"::tag",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Performance overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response times",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  { "title": "Performance over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Response times over time average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "k6-http-percentiles",
     "query": "SELECT mean(\"cq_mean_response_time\") FROM \"30d\".\"k6-http-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_mean_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times over time maximum",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "k6-http-percentiles",
     "query": "SELECT mean(\"cq_max_response_time\") FROM \"30d\".\"k6-http-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_max_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times over time stdDev",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "k6-http-percentiles",
     "query": "SELECT mean(\"cq_stddev_response_time\") FROM \"30d\".\"k6-http-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_stddev_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times over time 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "k6-http-percentiles",
     "query": "SELECT mean(\"cq_50pct_response_time\") FROM \"30d\".\"k6-http-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_50pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times over time 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "k6-http-percentiles",
     "query": "SELECT mean(\"cq_90pct_response_time\") FROM \"30d\".\"k6-http-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_90pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Response times over time 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "k6-http-percentiles",
     "query": "SELECT mean(\"cq_99pct_response_time\") FROM \"30d\".\"k6-http-percentiles\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"expected_response\"::tag = 'true') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_99pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "expected_response::tag", "operator": "=", "value": "true" }
     ]
    }
   ]
  }
 ]
}