{
 "title": "JMeter TimescaleDB Dashboard",
 "tags": [
  "perfana",
  "perfana-template",
  "no-anomaly-detection"
 ],
 "time": { "from": "2025-12-24T10:02:39.465Z", "to": "2025-12-24T10:11:22.541Z" },
 "templating": {
  "list": [
   { "name": "cagg_suffix", "label": "CAGG resolution", "query": "5s,1m,5m" },
   {
    "name": "system_under_test",
    "query": "select system_under_test from requests_raw"
   },
   {
    "name": "test_environment",
    "query": "select test_environment from requests_raw where system_under_test = '$system_under_test' "
   },
   {
    "name": "scenario_name",
    "query": "select scenario_name from requests_raw where system_under_test = '$system_under_test' AND test_environment = '$test_environment' "
   }
  ]
 },
 "panels": [
  {
   "title": "Current VU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualUsers",
     "query": "select sum(vusers) from (SELECT max(\"currentActiveThreads\") as vusers FROM \"virtualUsers\" WHERE time > ${__from}ms and time > now() - 20s GROUP BY \"nodeName\" fill(none)) fill(none)",
     "rawSql": "SELECT\n  SUM(max_threads_per_location) AS \"Total\"\nFROM (\n  SELECT\n    node_name,\n    MAX(active_threads) AS max_threads_per_location\n  FROM virtual_users\n  WHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n        $__timeFilter(time) AND\n        time > now() - interval '20 seconds'\n  GROUP BY 1\n  ORDER BY 1\n) sub\n\n"
    }
   ]
  },
  {
   "title": "Transactions per minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT count(\"responseTime\") FROM \"transactions\" WHERE time > now() - 1m and time > ${__from}ms",
     "rawSql": "SELECT\n  count(response_time)\nFROM transactions\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(time) AND\n      time > now() - interval '1 minutes'"
    }
   ]
  },
  {
   "title": "Successful RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"responseCode\") FROM \"requestsRaw\" WHERE success='true' AND time > now() - 1m and time > ${__from}ms",
     "rawSql": "SELECT\n  sum(response_time) \nFROM requests_raw\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND\n      $__timeFilter(time) AND\n      time > now() - interval '65 seconds' and time < now() - interval '5 seconds'\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsAggregated_10s",
     "query": "SELECT (sum(\"bytesIn\") + sum(\"bytesOut\")) / 10 * 8 FROM \"requestsAggregated_10s\" WHERE time > now() - 1m and time > ${__from}ms GROUP BY time(10s), \"requestName\" fill(null)",
     "rawSql": "SELECT\n  time_bucket('1 second', time) AS time,\n  (sum(response_size) + sum(request_size)) / 1 * 8 as \"Total Traffic\"\nFROM requests_raw\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND time > now() - interval '20 seconds' \nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requestsError",
     "query": "SELECT count(\"responseCode\") FROM \"requestsError\" WHERE  time > ${__from}ms AND $timeFilter GROUP BY time(1m) fill(0)",
     "rawSql": "SELECT\n  count(response_time)\nFROM requests_error\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Errors last 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsError",
     "query": "SELECT count(\"responseCode\") FROM \"requestsError\" WHERE time > ${__from}ms and time > now() - 1m fill(0)",
     "rawSql": "SELECT\n  count(response_time)\nFROM requests_error\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(time) AND\n      time > now() - interval '1 minutes'"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(EPOCH FROM (to_timestamp($__to/1000) - to_timestamp($__from/1000))) AS total_seconds;"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Concurrent Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', time) AS time,\n  SUM(max_threads_per_node) AS \"Total\"\nFROM (\n  SELECT\n    time_bucket('$__interval', time) AS time,\n    node_name,\n    MAX(active_threads) AS max_threads_per_node\n  FROM virtual_users\n  WHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) \n        AND $__timeFilter(time)\n  GROUP BY 1,2\n  ORDER BY 1,2\n) sub\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sum(bytes_in) as \"Bytes In\",\n  sum(bytes_out) as \"Bytes Out\",\n (sum(bytes_in) + sum(bytes_out)) / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) as \"Total Traffic\"\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Request Overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sum(n)::float / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) as \"Requests per second\",\n  sum(avg_rt * n) / NULLIF(sum(n), 0) as \"Response times\",\n  sum(avg_connect * n) / NULLIF(sum(n), 0) as \"TCP Connect\"\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sampler_name,\n  sum(n) as \"count\"\nFROM requests_error_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request Response Times",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_samplerName",
     "groupBy": [
      { "params": [ "${granularity}s" ], "type": "time" },
      { "params": [ "samplerName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requestsAggregated_10s",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sampler_name,\n  sum(avg_rt * n) / NULLIF(sum(n), 0) as \"Response times\"\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;",
     "tags": [
      { "condition": "AND", "key": "samplerName", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_samplerName",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "samplerName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requestsAggregated_10s",
     "query": "SELECT (count(\"count\")  / $granularity) as value FROM \"requestsRaw\" WHERE (\"success\" = 'true') AND $timeFilter GROUP BY time(${granularity}s), \"samplerName\" fill(null)",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sampler_name,\n  sum(n)::float / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) as count\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;",
     "tags": [
      { "key": "samplerName", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Passed vs Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sum(n_ok) AS \"Passed\",\n  sum(n_err) AS \"Failed\"\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Requests Error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sampler_name,\n  ROUND(\n    sum(n_err)::numeric / NULLIF(sum(n), 0),\n    4\n  ) AS \"Error (%)\"\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Transaction response times",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transactionName",
     "groupBy": [
      { "params": [ "${granularity}s" ], "type": "time" },
      { "params": [ "transactionName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT mean(\"responseTime\") FROM \"transactions\" WHERE (\"success\" = 'true' AND \"transactionName\"::tag =~ /^$Transactions$/) AND $timeFilter GROUP BY time(${granularity}s), \"transactionName\" fill(none)",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  transaction_name,\n  sum(avg_rt * n) / NULLIF(sum(n), 0) as avg_rt\nFROM transactions_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;",
     "tags": [
      { "key": "success", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "transactionName::tag", "operator": "=~", "value": "/^$Transactions$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "All Transactions",
     "groupBy": [
      { "params": [ "${granularity}s" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT (count(\"responseTime\")  / $granularity) as value FROM \"transactions\" WHERE (\"success\" = 'true') AND ( \"transactionName\"::tag =~ /^$Transactions$/) AND $timeFilter GROUP BY time(${granularity}s) fill(none)",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  transaction_name,\n  sum(n)::float / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) as count\nFROM transactions_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;",
     "tags": [
      { "key": "SUCCESS", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Passed vs Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  sum(n_ok) AS \"Passed\",\n  sum(n_err) AS \"Failed\"\nFROM transactions_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Transactions Error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  transaction_name,\n  ROUND(\n    sum(n_err)::numeric / NULLIF(sum(n), 0),\n    4\n  ) AS \"Error (%)\"\nFROM transactions_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND $__timeFilter(bucket)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsError",
     "query": "SELECT time, randomId, responseTime, nodeName, transactionName, samplerName, responseCode, url, responseMessage FROM \"requestsError\" WHERE (\"samplerName\"::tag =~ /^$URL$/) AND $timeFilter order by time desc limit 100",
     "rawSql": "SELECT\n  time,\n  sampler_name,\n  transaction_name,\n  response_time,\n  node_name,\n  random_id,\n  url,\n  response_code,\n  response_message\nFROM requests_error\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(time)\nORDER BY 1 DESC\nLIMIT 100;",
     "tags": [
      { "key": "requestName", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  { "title": "Location Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Location Response Times",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  location,\n  ROUND(sum(avg_rt * n) / NULLIF(sum(n), 0)) as avg_rt\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Node Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_location RPS",
     "groupBy": [
      { "params": [ "${granularity}s" ], "type": "time" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT (count(\"count\")  / $granularity) as value FROM \"requestsRaw\" WHERE (\"success\" = 'true') AND $timeFilter GROUP BY time(${granularity}s), \"samplerName\" fill(null)",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  location,\n  sum(n)::float / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) as count\nFROM requests_raw_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Node Errors",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_location $tag_nodeName Errors",
     "groupBy": [
      { "params": [ "${granularity}s" ], "type": "time" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "nodeName::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requestsError",
     "query": "SELECT (count(\"count\")  / $granularity) as value FROM \"requestsRaw\" WHERE (\"success\" = 'true') AND $timeFilter GROUP BY time(${granularity}s), \"samplerName\" fill(null)",
     "rawSql": "SELECT\n  time_bucket('$__interval', bucket) AS time,\n  node_name,\n  sum(n)::float / EXTRACT(EPOCH FROM '$__interval'::INTERVAL) as count\nFROM requests_error_${cagg_suffix}\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND \n      $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Transaction response time table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 }
  },
  {
   "title": "Response time table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "samplerName" ], "type": "tag" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT min(\"responseTime\"), mean(\"responseTime\"), max(\"responseTime\"), count(\"responseTime\") FROM \"transactions\" WHERE \"success\" = 'true' AND $timeFilter GROUP BY \"transactionName\"",
     "rawSql": "SELECT\n  transaction_name,\n  min(min_rt) AS min_response_time,\n  ROUND(sum(avg_rt * n) / NULLIF(sum(n), 0)) AS avg_response_time,\n  max(max_rt) AS max_response_time,\n  sum(n) AS total,\n  sum(n_ok) AS passed,\n  sum(n_err) AS failed,\n  ROUND(\n    sum(n_err)::numeric / NULLIF(sum(n), 0),\n    4\n  ) AS error_percentage\nFROM transactions_5m\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND\n      $__timeFilter(bucket)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  { "title": "Request response time table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Response time table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "samplerName" ], "type": "tag" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT min(\"responseTime\"), mean(\"responseTime\"), max(\"responseTime\"), count(\"responseCode\") FROM \"requestsRaw\" WHERE \"success\"='true' AND $timeFilter GROUP BY \"transactionName\", \"samplerName\"",
     "rawSql": "SELECT\n  sampler_name,\n  transaction_name,\n  min(min_rt) AS min_response_time,\n  ROUND(sum(avg_rt * n) / NULLIF(sum(n), 0)) AS avg_response_time,\n  max(max_rt) AS max_response_time,\n  sum(n) AS total,\n  sum(n_ok) AS passed,\n  sum(n_err) AS failed,\n  ROUND(\n    sum(n_err)::numeric / NULLIF(sum(n), 0),\n    4\n  ) AS error_percentage\nFROM requests_raw_5m\nWHERE system_under_test = '$system_under_test' AND test_environment = '$test_environment' AND scenario_name IN ($scenario_name) AND\n      $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  }
 ]
}