{
 "title": "Neoload",
 "tags": [
  "perfana",
  "perfana-template",
  "perfana-performance-test-tool",
  "neoload"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": "show tag values  from resultTimeseries with key=\"systemUnderTest\""
   },
   {
    "name": "test_environment",
    "query": "show tag values from resultTimeseries with key=\"testEnvironment\" where \"systemUnderTest\" =~ /$system_under_test/"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean overall response times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_elementType",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "elementType::tag" ], "type": "tag" }
     ],
     "measurement": "elementTimeSeries",
     "query": "SELECT mean(\"avgDuration\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"elementType\"::tag",
     "select": [
      [
       { "params": [ "avgDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_elementType",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "elementType::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"elementsPerSecond\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($interval), \"elementType\"::tag",
     "select": [
      [
       { "params": [ "elementsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_elementType",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "elementType::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"errorRate\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($interval), \"elementType\"::tag",
     "select": [
      [
       { "params": [ "errorRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput per transaction",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "elementTimeSeries",
     "query": "SELECT mean(\"elementsPerSecond\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($interval), \"userPath\"::tag, \"name\"::tag",
     "select": [
      [
       { "params": [ "elementsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Throughput per request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_parent $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" }
     ],
     "measurement": "elementTimeSeries",
     "query": "SELECT mean(\"elementsPerSecond\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'REQUEST') AND $timeFilter GROUP BY time($interval), \"userPath\"::tag, \"name\"::tag, \"parent\"::tag",
     "select": [
      [
       { "params": [ "elementsPerSecond" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "REQUEST" }
     ]
    }
   ]
  },
  {
   "title": "Error rate per transaction",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" }
     ],
     "measurement": "elementTimeSeries",
     "query": "SELECT mean(\"errorRate\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($interval), \"name\"::tag, \"userPath\"::tag",
     "select": [
      [
       { "params": [ "errorRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Error rate per request",
   "type": "timeseries",
   "description": "perfana-request-names",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_parent $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" }
     ],
     "measurement": "elementTimeSeries",
     "query": "SELECT mean(\"errorRate\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'REQUEST') AND $timeFilter GROUP BY time($interval), \"name\"::tag, \"userPath\"::tag, \"parent\"::tag",
     "select": [
      [
       { "params": [ "errorRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "REQUEST" }
     ]
    }
   ]
  },
  {
   "title": "Passed vs Failed transactions",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_name $tag_result",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT last(\"passed\"), last(\"errors\"), last(\"count\") FROM \"30d\".\"elementValues\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY \"name\", \"userPath\"::tag, \"parent\"::tag",
     "select": [
      [
       { "params": [ "passed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Passed vs Failed requests",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_name $tag_result",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT last(\"passed\"), last(\"errors\"), last(\"count\") FROM \"30d\".\"elementValues\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'REQUEST') AND $timeFilter GROUP BY \"name\", \"userPath\"::tag, \"parent\"::tag",
     "select": [
      [
       { "params": [ "passed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "REQUEST" }
     ]
    }
   ]
  },
  {
   "title": "Error messages count",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "alias": "$tag_name $measurement ",
     "groupBy": [
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "code::tag" ], "type": "tag" },
      { "params": [ "request::tag" ], "type": "tag" },
      { "params": [ "transaction::tag" ], "type": "tag" }
     ],
     "measurement": "errors",
     "query": "SELECT count(\"message\") FROM \"30d\".\"errors\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY \"userPath\"::tag, \"code\"::tag, \"request\"::tag, \"transaction\"::tag",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_transaction $tag_request $tag_code",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "request::tag" ], "type": "tag" },
      { "params": [ "transaction::tag" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "code::tag" ], "type": "tag" }
     ],
     "measurement": "errors",
     "query": "SELECT count(\"message\") FROM \"30d\".\"errors\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($interval), \"request\"::tag, \"transaction\"::tag, \"userPath\"::tag, \"code\"::tag",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Concurrent users",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "resultTimeSeries",
     "query": "SELECT mean(\"userLoad\") FROM \"30d\".\"resultTimeSeries\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"nodeName\"::tag fill(null)",
     "select": [
      [
       { "params": [ "userLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  { "title": "Transaction response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Transaction response times overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT last(\"perc50\"), last(\"perc90\"), last(\"perc95\"), last(\"perc99\"), last(\"minDuration\"), last(\"avgDuration\"), last(\"maxDuration\") FROM \"30d\".\"elementValues\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY \"name\", \"userPath\"::tag, \"name\"::tag",
     "select": [
      [
       { "params": [ "perc50" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "perc90" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "perc95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "perc99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "minDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "avgDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "maxDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Transaction response times minimum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"minDuration\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag",
     "select": [
      [
       { "params": [ "minDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Transaction response times maximum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"maxDuration\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag",
     "select": [
      [
       { "params": [ "maxDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Transaction response times average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"avgDuration\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag",
     "select": [
      [
       { "params": [ "avgDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Transaction response times 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"perc50\") FROM \"30d\".\"elementValues\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag",
     "select": [
      [
       { "params": [ "perc50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Transaction response times 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"perc90\") FROM \"30d\".\"elementValues\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag",
     "select": [
      [
       { "params": [ "perc90" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Transaction response times 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"perc99\") FROM \"30d\".\"elementValues\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'TRANSACTION') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag",
     "select": [
      [
       { "params": [ "perc99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  { "title": "Request response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Requests response times overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT last(\"minDuration\"), last(\"avgDuration\"), last(\"maxDuration\") FROM \"30d\".\"elementValues\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"elementType\"::tag = 'REQUEST') AND $timeFilter GROUP BY \"name\", \"userPath\"::tag, \"parent\"::tag, \"name\"::tag",
     "select": [
      [
       { "params": [ "minDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "avgDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "maxDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "REQUEST" }
     ]
    }
   ]
  },
  {
   "title": "Request response times minimum",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_parent $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"minDuration\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'REQUEST') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag, \"parent\"::tag",
     "select": [
      [
       { "params": [ "minDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "REQUEST" }
     ]
    }
   ]
  },
  {
   "title": "Request response times maximum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_parent $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"maxDuration\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'REQUEST') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag, \"parent\"::tag",
     "select": [
      [
       { "params": [ "maxDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "REQUEST" }
     ]
    }
   ]
  },
  {
   "title": "Request response times average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_userPath $tag_parent $tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "userPath::tag" ], "type": "tag" },
      { "params": [ "parent::tag" ], "type": "tag" }
     ],
     "measurement": "elementValues",
     "query": "SELECT mean(\"avgDuration\") FROM \"30d\".\"elementTimeSeries\" WHERE (\"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"elementType\"::tag = 'REQUEST') AND $timeFilter GROUP BY time($__interval), \"name\", \"userPath\"::tag, \"parent\"::tag",
     "select": [
      [
       { "params": [ "avgDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "elementType::tag", "operator": "=", "value": "REQUEST" }
     ]
    }
   ]
  }
 ]
}