{
 "title": "Gatling Request Performance",
 "tags": [
  "perfana",
  "perfana-template",
  "Performance",
  "Gatling"
 ],
 "time": { "from": "2024-02-27T14:23:42.745Z", "to": "2024-02-27T14:30:49.997Z" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": "show tag values  from requests with key=\"systemUnderTest\""
   },
   {
    "name": "test_environment",
    "query": "show tag values from requests with key=\"testEnvironment\" where \"systemUnderTest\" =~ /$system_under_test/"
   },
   {
    "name": "simulation",
    "query": "show tag values from requests with key= \"simulation\" where \"systemUnderTest\" =~ /$system_under_test/ and \"testEnvironment\" =~ /$test_environment/"
   },
   {
    "name": "requestName",
    "query": "show tag values from requests with key= \"name\" where \"systemUnderTest\" =~ /$system_under_test/ and \"testEnvironment\" =~ /$test_environment/ and \"simulation\" =~ /$simulation/"
   }
  ]
 },
 "panels": [
  {
   "title": "Response time minimum",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "minimum",
     "measurement": "requests",
     "query": "SELECT min(\"duration\") FROM \"30d\".\"requests\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"simulation\" =~ /^$simulation$/ AND \"name\" =~ /^$requestName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Response time mean",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "mean",
     "measurement": "requests",
     "query": "SELECT mean(\"duration\") FROM \"30d\".\"requests\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"simulation\" =~ /^$simulation$/ AND \"name\" =~ /^$requestName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Response time 95th percentile",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "95th percentile",
     "measurement": "requests",
     "query": "SELECT percentile(\"duration\", 95) FROM \"30d\".\"requests\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"simulation\" =~ /^$simulation$/ AND \"name\" =~ /^$requestName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Response time 99th percentile",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "99th percentile",
     "measurement": "requests",
     "query": "SELECT percentile(\"duration\", 99) FROM \"30d\".\"requests\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"simulation\" =~ /^$simulation$/ AND \"name\" =~ /^$requestName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Response time maximum",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "maximum",
     "measurement": "requests",
     "query": "SELECT max(\"duration\") FROM \"30d\".\"requests\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"simulation\" =~ /^$simulation$/ AND \"name\" =~ /^$requestName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Response time standard deviation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "standard deviation",
     "measurement": "requests",
     "query": "SELECT stddev(\"duration\") FROM \"30d\".\"requests\" WHERE (\"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"simulation\" =~ /^$simulation$/ AND \"name\" =~ /^$requestName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "requests",
     "query": "SELECT \"percentiles99\" FROM \"gatling2\" WHERE  \"simulation\" =~ /^$simulation$/ AND \"result\" = 'ok' AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "requests",
     "query": "SELECT \"percentiles99\" FROM \"gatling2\" WHERE  \"simulation\" =~ /^$simulation$/ AND \"result\" = 'ok' AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Response times raw data",
   "type": "timeseries",
   "description": "perfana-response-times",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT \"duration\" FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK' AND \"name\" =~ /^$requestName$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_name  |  $tag_errorMessage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "errorMessage" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'KO' AND \"name\" =~ /^$requestName$/) AND $timeFilter GROUP BY time(10s), \"name\", \"errorMessage\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$requestName$/" }
     ]
    }
   ]
  }
 ]
}