{
 "title": "Docker container metrics",
 "description": "Fixed queries and added network metrics.",
 "tags": [
  "perfana",
  "docker",
  "perfana-template"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "show tag values  from docker_container_cpu with key=\"system_under_test\""
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "show tag values  from docker_container_cpu with key=\"test_environment\" where \"system_under_test\" =~ /$system_under_test/"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "show tag values from docker_container_cpu with key=\"container_name\" where \"system_under_test\" =~ /$system_under_test/ and \"test_environment\" =~ /$test_environment/"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") FROM \"30d\".\"docker_container_cpu\" WHERE (\"container_name\" =~ /^$container$/ AND \"system_under_test\" =~ /^$system_under_test$/ AND \"test_environment\" =~ /^$test_environment$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "system_under_test::tag", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "test_environment::tag", "operator": "=~", "value": "/^$test_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "IO service recursive read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "query": "SELECT mean(\"io_service_bytes_recursive_read\") FROM \"30d\".\"docker_container_blkio\" WHERE (\"container_name\" =~ /^$container$/ AND \"system_under_test\" =~ /^$system_under_test$/ AND \"test_environment\" =~ /^$test_environment$/)  AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_read"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "IO service recursive write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_write"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") FROM \"30d\".\"docker_container_mem\" WHERE (\"container_name\" =~ /^$container$/ AND \"system_under_test\" =~ /^$system_under_test$/ AND \"test_environment\" =~ /^$test_environment$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Recived",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT mean(\"rx_bytes\") FROM \"30d\".\"docker_container_net\" WHERE (\"container_name\" =~ /^$container$/ AND \"system_under_test\" =~ /^$system_under_test$/ AND \"test_environment\" =~ /^$test_environment$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Transmited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  }
 ]
}