{
 "title": "Kubernetes Namespace Resources",
 "description": "Dashboard showing namespace resources",
 "tags": [
  "kubernetes",
  "perfana",
  "perfana-template"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_environment", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU limits",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"^$test_environment$\"}) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pods CPU usage as percentage of limit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(100 * label_join(label_join(sum by(container, namespace, pod) (rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"^$test_environment$\"}[1m])), \"pod\", \"\", \"pod\"), \"container\", \"\", \"container\") / avg by( container, namespace, pod) (kube_pod_container_resource_limits{resource=\"cpu\"})) ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(kube_pod_container_status_restarts_total {namespace=~\"^$test_environment$\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttling %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{namespace=~\"^$test_environment$\", container_name!=\"POD\", image!=\"\"} [1m]) / rate(container_cpu_cfs_periods_total{namespace=~\"^$test_environment$\", container_name!=\"POD\", image!=\"\"} [1m] ) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory limits",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"^$test_environment$\"}) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$test_environment\"}) by (pod, node)",
     "legendFormat": "{{pod}} on {{node}}"
    }
   ]
  }
 ]
}