{
 "title": "JVM",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "tags": [
  "Perfana",
  "perfana-template",
  "JVM",
  "$service"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, system_under_test)"
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{system_under_test=\"$system_under_test\"}, test_environment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"},service)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_cpu_usage{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_pod_name)",
     "legendFormat": "system"
    },
    {
     "expr": "avg(process_cpu_usage{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_pod_name)",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(system_load_average_1m{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_pod_name)",
     "legendFormat": "system load average 1m"
    },
    {},
    {
     "expr": "system_cpu_count{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}",
     "legendFormat": "cpu count"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(jvm_threads_live_threads{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_pod_name)",
     "legendFormat": "live"
    },
    {
     "expr": "avg(jvm_threads_daemon_threads{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_pod_name)",
     "legendFormat": "daemon"
    },
    {
     "expr": "avg(jvm_threads_peak_threads{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_pod_name)",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(jvm_threads_states_threads{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_pod_name, state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events (1m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(process_open_fds{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_name)",
     "legendFormat": "{{ kubernetes_name }} open fds"
    },
    {
     "expr": "avg(process_max_fds{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_name)",
     "legendFormat": "{{ kubernetes_name }} max  ffds"
    },
    {
     "expr": "avg(process_files_open_files{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_name)",
     "legendFormat": "{{ kubernetes_name }} open files"
    },
    {
     "expr": "avg(process_files_max_files{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_name)",
     "legendFormat": "{{ kubernetes_name }} max open files"
    }
   ]
  }
 ]
}