{
 "title": "Gatling",
 "tags": [
  "perfana",
  "perfana-template",
  "perfana-performance-test-tool",
  "gatling"
 ],
 "time": { "from": "2024-04-30T08:33:47.408Z", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": "show tag values  from requests with key=\"systemUnderTest\""
   },
   {
    "name": "test_environment",
    "query": "show tag values from requests with key=\"testEnvironment\" where \"systemUnderTest\" =~ /$system_under_test/"
   },
   {
    "name": "simulation",
    "query": "show tag values from requests with key= \"simulation\" where \"systemUnderTest\" =~ /$system_under_test/ and \"testEnvironment\" =~ /$test_environment/"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean overall response times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "mean response time",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "requests",
     "query": "SELECT mean(\"duration\") FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeName::tag" ], "type": "tag" },
      { "params": [ "scenario::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "users",
     "query": "select sum(value) from (SELECT max(\"active\") as value FROM \"30d\".\"users\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"nodeName\"::tag, \"scenario\"::tag) where $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "alias": "Users for load generator: $tag_nodeName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "users",
     "query": "select sum(value) from (SELECT max(\"active\") as value FROM \"30d\".\"users\" WHERE (\"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"nodeName\"::tag, \"scenario\"::tag) where $timeFilter group by time($__interval), \"nodeName\"",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Total passed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Requests per second",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Total failed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Errors per second",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'KO') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" }
     ]
    }
   ]
  },
  {
   "title": "Passed requests per second",
   "type": "timeseries",
   "description": "perfana-request-names",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Failed requests per second",
   "type": "timeseries",
   "description": "perfana-request-names",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'KO') AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" }
     ]
    }
   ]
  },
  {
   "title": "Error messages count",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "$tag_name $measurement ",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "errorMessage" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\") FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'KO') AND $timeFilter GROUP BY \"name\", \"errorMessage\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" }
     ]
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_name $tag_errorMessage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "errorMessage" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  / 10 FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'KO') AND $timeFilter GROUP BY time($interval), \"name\", \"errorMessage\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" }
     ]
    }
   ]
  },
  {
   "title": "Number of requests OK vs KO",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_name $tag_result",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\")  as \"OK\" FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"result\" = 'OK' AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "alias": "$tag_name $tag_result",
     "description": "perfana-request-names",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT count(\"duration\") as \"KO\"  FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"result\" = 'KO' AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentage failed requests",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Cumulative % failed",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "errorMessage" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT (CUMULATIVE_SUM(mean(\"failed\"))  /  CUMULATIVE_SUM(mean(\"total\")) ) * 100 FROM \"30d\".\"gatling-throughput\"  WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/) AND $timeFilter group by time(10s) fill(0)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "KO" }
     ]
    }
   ]
  },
  {
   "title": "Performance overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Response times",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "requests",
       "query": "SELECT mean(\"duration\"), min(\"duration\"), percentile(\"duration\", 50), percentile(\"duration\", 90), percentile(\"duration\", 99), max(\"duration\"), count(\"duration\") FROM \"30d\".\"requests\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
        { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
        { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Performance over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Average Response times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "gatling-percentiles",
     "query": "SELECT mean(\"cq_mean_response_time\") FROM \"30d\".\"gatling-percentiles\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_mean_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Response times maximum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "gatling-percentiles",
     "query": "SELECT mean(\"cq_max_response_time\") FROM \"30d\".\"gatling-percentiles\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_max_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Response times stdDev",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "gatling-percentiles",
     "query": "SELECT mean(\"cq_stddev_response_time\") FROM \"30d\".\"gatling-percentiles\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_stddev_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Response times 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "gatling-percentiles",
     "query": "SELECT mean(\"cq_50pct_response_time\") FROM \"30d\".\"gatling-percentiles\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_50pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Response times 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "gatling-percentiles",
     "query": "SELECT mean(\"cq_90pct_response_time\") FROM \"30d\".\"gatling-percentiles\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_90pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Response times 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "gatling-percentiles",
     "query": "SELECT mean(\"cq_99pct_response_time\") FROM \"30d\".\"gatling-percentiles\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"testEnvironment\" =~ /^$test_environment$/ AND \"systemUnderTest\" =~ /^$system_under_test$/ AND \"result\" = 'OK') AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "cq_99pct_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "testEnvironment", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest", "operator": "=~", "value": "/^$system_under_test$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "OK" }
     ]
    }
   ]
  }
 ]
}