{
 "title": "Kubernetes Pod Metrics",
 "description": "Kubernetes pod metrics",
 "tags": [
  "perfana",
  "kubernetes",
  "perfana-template"
 ],
 "time": { "from": "2023-11-13T12:34:00.416Z", "to": "2023-11-13T12:34:41.791Z" },
 "templating": {
  "list": [
   { "name": "test_environment", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$test_environment\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods CPU usage % of limit (2m avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(100 * label_join(label_join(sum by(pod, namespace,node) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",namespace=~\"$test_environment\", pod=~\"^$pod.*\"}[2m])), \"pod\", \"\", \"pod\"), \"container\", \"\", \"container\") / avg by(pod, namespace, node) (kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$test_environment\", pod=~\"^$pod.*\"})) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average pods CPU usage % of limit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(round(100 * label_join(label_join(sum by(pod, namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",namespace=~\"$test_environment\", pod=~\"^$pod.*\"}[2m])), \"pod\", \"\", \"pod\"), \"container\", \"\", \"container\") / avg by(pod, namespace) (kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$test_environment\", pod=~\"^$pod.*\"})) )",
     "legendFormat": "Average pod CPU usage"
    }
   ]
  },
  {
   "title": "CPU Throttling %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$test_environment\", container_name!=\"POD\", image!=\"\", pod=~\"^$pod.*\"} [2m]) / rate(container_cpu_cfs_periods_total{namespace=~\"$test_environment\", container_name!=\"POD\", image!=\"\", pod=~\"^$pod.*\"} [2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", pod=~\"^$pod.*\", namespace=~\"$test_environment\"}) by (pod, node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{pod=~\"^$pod.*\", namespace=~\"$test_environment\"}[10m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}