{
 "title": "JVM springboot legacy",
 "description": "Dashboard legacy applications (Java, Spring Boot)",
 "tags": [
  "perfana",
  "perfana-template",
  "JVM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "label_values(jvm_memory_bytes_used, system_under_test)"
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{system_under_test=\"$system_under_test\"}, test_environment)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_used{ system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(systemload_average{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(threads{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "threads"
    },
    {
     "expr": "avg(threads_peak{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "peak"
    },
    {
     "expr": "avg(threads_daemon{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "daemon"
    },
    {
     "expr": "process_threads{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Process CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[30s])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Process Memory", "type": "timeseries", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 }, "fieldConfig": { "defaults": { "unit": "bytes" } } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "mem{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}",
     "legendFormat": "mem"
    },
    {
     "expr": "mem_free{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}",
     "legendFormat": "mem_free"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(process_open_fds{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "{{ kubernetes_name }} open fds"
    },
    {
     "expr": "avg(process_max_fds{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "{{ kubernetes_name }} max  ffds"
    },
    {
     "expr": "avg(process_files_open_files{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_name)",
     "legendFormat": "{{ kubernetes_name }} open files"
    },
    {
     "expr": "avg(process_files_max_files{service=\"$service\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(kubernetes_name)",
     "legendFormat": "{{ kubernetes_name }} max open files"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\"}) by(instance)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\"}) by(instance)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"heap\"}) by(instance)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\"}) by(instance)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\"}) by(instance)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", area=\"nonheap\"}) by(instance)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}) by(instance)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Young Generation count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(gc_g1_young_generation_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}} {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "G1 Young Generation time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(gc_g1_young_generation_time{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m])/rate(gc_g1_young_generation_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m])) ",
     "legendFormat": "{{kubernetes_pod_name}} {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "G1 Old Generation count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(gc_g1_old_generation_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}} {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "G1 Old Generation time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(gc_g1_old_generation_time{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m])/rate(gc_g1_old_generation_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m])) ",
     "legendFormat": "{{kubernetes_pod_name}} {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "counter_status_200_metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(counter_status_200_metrics{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m])) by(instance)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "counter_status_500_carts_customerId_items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(counter_status_500_carts_customerId_items{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}[1m])) by(instance)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "gauge_response_metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gauge_response_metrics{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "gauge_response_carts_customerId_items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gauge_response_carts_customerId_items{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Eden Space\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Eden Space\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Eden Space\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Old Gen\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Old Gen\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Old Gen\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Survivor Space\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Survivor Space\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"G1 Survivor Space\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Compressed Class Space\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Compressed Class Space\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Compressed Class Space\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Code Cache\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Code Cache\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Code Cache\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Metaspace\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Metaspace\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", pool=~\"Metaspace\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}