{
 "title": "HTTP client requests",
 "description": "Dashboard for consumed http requests",
 "tags": [
  "perfana",
  "perfana-template",
  "requests"
 ],
 "time": { "from": "2023-07-28T08:28:20.007Z", "to": "2023-07-28T08:36:58.071Z" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "label_values(http_client_requests_seconds_count,system_under_test)"
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{system_under_test=\"$system_under_test\"},test_environment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per second by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", uri!~\".*(subscribe|events|echo|actuator).*\"}[2m])) by(status)",
     "legendFormat": "{{status}} "
    }
   ]
  },
  {
   "title": "Requests response times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(http_client_requests_seconds_sum{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", uri!~\".*(subscribe|events|echo|actuator).*\" }[1m])) / avg(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", uri!~\".*(subscribe|events|echo|actuator).*\"}[1m]))",
     "legendFormat": "Average response times"
    }
   ]
  },
  {
   "title": "% failed requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", uri!~\".*(subscribe|events|echo|actuator).*\", status!~\"(2|3).*\" }[1m])) / sum(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", uri!~\".*(subscribe|events|echo|actuator).*\"}[1m])) * 100",
     "legendFormat": "% failed requests"
    }
   ]
  },
  { "title": "Statuscode 2.*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Requests per second status=2.*",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status=~\"2.*\", uri!~\".*(subscribe|events|echo|actuator).*\"}[2m])) by(method, uri, status)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests response times status=2.*",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status=~\"2.*\", uri!~\".*(subscribe|events|echo|actuator).*\"}[1m]) / rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status=~\"2.*\", uri!~\".*(subscribe|events|echo|actuator).*\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests per second status=2.*",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status=~\"2.*\"}[2m])) by(method, uri, status)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests response times status=2.*",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status=~\"2.*\"}[1m]) / rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status=~\"2.*\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  { "title": "Statuscode !2.*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Requests per second status !=2.*",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status!~\"2.*\", uri!~\".*(subscribe|events|echo|actuator).*\"}[2m])) by(method, uri, status)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests response times status !=2.*",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status!~\"2.*\", uri!~\".*(subscribe|events|echo|actuator).*\"}[1m]) / rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status!~\"2.*\", uri!~\".*(subscribe|events|echo|actuator).*\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests per second status=2.*",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status!~\"2.*\"}[2m])) by(method, uri, status)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests response times status !=2.*",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status!~\"2.*\"}[1m]) / rate(http_client_requests_seconds_count{service=~\"^$service.*\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\", status!~\"2.*\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}