{
 "title": "Hikari Connection Pool",
 "description": "HikariCP",
 "tags": [
  "Perfana",
  "Perfana-template",
  "database",
  "JVM"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "label_values(hikaricp_connections, system_under_test)"
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "label_values(hikaricp_connections{system_under_test=\"$system_under_test\"}, test_environment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(hikaricp_connections{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hikari connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_active{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}) by(pool, pod)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_idle{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}) by(pool, pod)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Pending connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_pending{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}) by(pool, pod)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "Connections time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Acquire time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_acquire_seconds_sum{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m])  / irate(hikaricp_connections_acquire_seconds_count{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m]) ",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Usage time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_sum{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m]) / irate(hikaricp_connections_usage_seconds_count{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Queries / second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_count{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Timeout total time",
   "type": "timeseries",
   "description": "hikaricp_connections_timeout_total\n\ntimeout total time per second",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_timeout_total{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Creation time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_creation_seconds_sum{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m]) / irate(hikaricp_connections_creation_seconds_count{service=~\"$service\", system_under_test=~\"$system_under_test\", test_environment=~\"$test_environment\"}[2m])",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}