organizationId: e4a8ca8d-0363-4ac5-8491-a89c8aa24931
items:
  - dashboardUid: gatling-overview-influxdb
    dashboardLabel: Gatling
    panelId: 6
    panelTitle: Passed requests per second
    metricClassification: RED_rate
    higherIsBetter: true
  - dashboardUid: gatling-overview-influxdb
    dashboardLabel: Gatling
    panelId: 38
    panelTitle: Total passed requests per second
    metricClassification: RED_rate
    higherIsBetter: true
  - dashboardUid: gatling-overview-influxdb
    dashboardLabel: Gatling
    panelId: 37
    panelTitle: Total failed requests per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: gatling-overview-influxdb
    dashboardLabel: Gatling
    panelId: 39
    panelTitle: Failed requests per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: gatling-overview-influxdb
    dashboardLabel: Gatling
    panelId: 45
    panelTitle: Percentage failed requests
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: gatling-overview-influxdb
    dashboardLabel: Gatling
    panelId: 44
    panelTitle: Errors per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: gatling-overview-influxdb
    dashboardLabel: Gatling
    panelId: 52
    panelTitle: Response times 50th percentile
    metricClassification: RED_duration
    higherIsBetter: false
    absThreshold: 25


  - dashboardUid: neoload-overview-influxdb
    dashboardLabel: Neoload
    panelId: 6
    panelTitle: Passed requests per second
    metricClassification: RED_rate
    higherIsBetter: true
  - dashboardUid: neoload-overview-influxdb
    dashboardLabel: Neoload
    panelId: 38
    panelTitle: Total passed requests per second
    metricClassification: RED_rate
    higherIsBetter: true
  - dashboardUid: neoload-overview-influxdb
    dashboardLabel: Neoload
    panelId: 37
    panelTitle: Total failed requests per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: neoload-overview-influxdb
    dashboardLabel: Neoload
    panelId: 39
    panelTitle: Failed requests per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: neoload-overview-influxdb
    dashboardLabel: Neoload
    panelId: 45
    panelTitle: Percentage failed requests
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: neoload-overview-influxdb
    dashboardLabel: Neoload
    panelId: 44
    panelTitle: Errors per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: neoload-overview-influxdb
    dashboardLabel: Neoload
    panelId: 66
    panelTitle: Transaction response times average
    metricClassification: RED_duration
    higherIsBetter: false
    absThreshold: 0.02




  - dashboardUid: k6-http-overview-influxdb
    dashboardLabel: K6 http
    panelId: 6
    panelTitle: Passed requests per second
    metricClassification: RED_rate
    higherIsBetter: true
  - dashboardUid: k6-http-overview-influxdb
    dashboardLabel: K6 http
    panelId: 38
    panelTitle: Total passed requests per second
    metricClassification: RED_rate
    higherIsBetter: true
  - dashboardUid: k6-http-overview-influxdb
    dashboardLabel: K6 http
    panelId: 37
    panelTitle: Total failed requests per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: k6-http-overview-influxdb
    dashboardLabel: K6 http
    panelId: 39
    panelTitle: Failed requests per second
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: k6-http-overview-influxdb
    dashboardLabel: K6 http
    panelId: 45
    panelTitle: Percentage failed requests
    metricClassification: RED_errors
    higherIsBetter: false
  - dashboardUid: k6-http-overview-influxdb
    dashboardLabel: K6 http
    panelId: 44
    panelTitle: Errors per second
    metricClassification: RED_errors
    higherIsBetter: false

  - dashboardUid: kubernetes-namespace-resources-mimir
    dashboardLabel: Kubernetes Namespace Resources
    panelId: 16
    panelTitle: Pods CPU usage as percentage of limit
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: kubernetes-namespace-resources-mimir
    dashboardLabel: Kubernetes Namespace Resources
    panelId: 20
    panelTitle: Pods memory usage
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: kubernetes-namespace-resources-mimir
    dashboardLabel: Kubernetes Namespace Resources
    panelId: 24
    panelTitle: Container restarts
    metricClassification: USE_errors
    higherIsBetter: false
  - dashboardUid: kubernetes-namespace-resources-mimir
    dashboardLabel: Kubernetes Namespace Resources
    panelId: 22
    panelTitle: CPU Throttling %
    metricClassification: USE_saturation
    higherIsBetter: false
  - dashboardUid: kubernetes-pod-metrics-mimir
    dashboardLabel: Kubernetes Pod Metrics
    panelId: 99
    panelTitle: Average pods CPU usage % of limit
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: kubernetes-pod-metrics-mimir
    dashboardLabel: Kubernetes Pod Metrics
    panelId: 36
    panelTitle: Pods memory usage
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-mimir
    dashboardLabel: JVM
    panelId: 32
    panelTitle: Threads
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-mimir
    dashboardLabel: JVM
    panelId: 166
    panelTitle: Thread States
    metricClassification: USE_saturation
    higherIsBetter: false
    absThreshold: 10
  - dashboardUid: spring-boot-kubernetes-hickari-cp-mimir
    dashboardLabel: Hikari Connection Pool
    panelId: 18
    panelTitle: Idle connections
    metricClassification: USE_utilization
    higherIsBetter: true
  - dashboardUid: spring-boot-kubernetes-hickari-cp-mimir
    dashboardLabel: Hikari Connection Pool
    panelId: 10
    panelTitle: Active connections
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-hickari-cp-mimir
    dashboardLabel: Hikari Connection Pool
    panelId: 25
    panelTitle: Queries / second
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-hickari-cp-mimir
    dashboardLabel: Hikari Connection Pool
    panelId: 24
    panelTitle: Timeout total time
    metricClassification: USE_errors
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-hickari-cp-mimir
    dashboardLabel: Hikari Connection Pool
    panelId: 23
    panelTitle: Usage time
    metricClassification: USE_utilization
    higherIsBetter: false
    ignore: true
    ignoreMeanDiffSmallerThan: 10
  - dashboardUid: spring-boot-kubernetes-hickari-cp-mimir
    dashboardLabel: Hikari Connection Pool
    panelId: 16
    panelTitle: Acquire time
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-hickari-cp-mimir
    dashboardLabel: Hikari Connection Pool
    panelId: 19
    panelTitle: Pending connections
    metricClassification: USE_saturation
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 98
    panelTitle: Collections end of minor GC by cause
    metricClassification: USE_saturation
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 101
    panelTitle: Average Pause Durations end of minor GC by cause
    metricClassification: USE_saturation
    higherIsBetter: false
    absThreshold: 0.1
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 151
    panelTitle: Maximum Pause Durations end of minor GC by cause
    metricClassification: USE_saturation
    higherIsBetter: false
    absThreshold: 0.1
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 99
    panelTitle: Young generation memory pool increase
    metricClassification: USE_saturation
    higherIsBetter: false
    absThreshold: 25000000
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 176
    panelTitle: Collections end of major GC by cause
    metricClassification: USE_saturation
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 177
    panelTitle: Average Pause Durations end of major GC by cause
    metricClassification: USE_saturation
    higherIsBetter: false
    absThreshold: 0.1
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 178
    panelTitle: Maximum Pause Durations end of major GC by cause
    metricClassification: USE_saturation
    higherIsBetter: false
    absThreshold: 0.1
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 179
    panelTitle: Old generation memory pool increase
    metricClassification: USE_saturation
    higherIsBetter: false
    absThreshold: 25000000
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 24
    panelTitle: Average JVM Heap % used
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 25
    panelTitle: Average JVM Non-Heap % used
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 26
    panelTitle: Average JVM Total % used
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 163
    panelTitle: Average Eden Space in use
    metricClassification: USE_utilization
    higherIsBetter: false
    absThreshold: 25000000
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 172
    panelTitle: Average Survivor Space in use
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 175
    panelTitle: Average Old Gen in use
    metricClassification: USE_utilization
    higherIsBetter: false
    absThreshold: 25000000
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 78
    panelTitle: Average CodeHeap 'non-nmethods' % in use
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 154
    panelTitle: Average CodeHeap 'non-profiled nmethods' % in use
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 157
    panelTitle: Average CodeHeap 'profiled nmethods' % in use
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-jvm-g1gc-mimir
    dashboardLabel: JVM memory management G1GC
    panelId: 160
    panelTitle: Average Compressed Class Space % in use
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: spring-boot-kubernetes-httpconpool-mimir
    dashboardLabel: HTTP connection pool
    panelId: 106
    panelTitle: HTTP connection pool in use
    metricClassification: USE_utilization
    higherIsBetter: false
    absThreshold: 0.1

  - dashboardUid: spring-boot-kubernetes-jvm-mimir
    dashboardLabel: JVM
    panelId: 1
    panelTitle: Log Events (1m)
    metricClassification: USE_errors
    higherIsBetter: false


  - dashboardUid: bc53520866e45005fc33f9a3c7e4c92f
    dashboardLabel: Unknown Dashboard
    panelId: 64
    panelTitle: 95th percentile span durations
    metricClassification: RED_duration
    higherIsBetter: false
    absThreshold: 0.05


  - dashboardUid: span-metrics
    dashboardLabel: Span metrics
    panelId: 64
    panelTitle: 95th percentile span durations
    metricClassification: RED_duration
    higherIsBetter: false
  - dashboardUid: docker-telegraf-influxdb
    dashboardLabel: Docker container metrics
    panelId: 1
    panelTitle: CPU
    metricClassification: USE_utilization
    higherIsBetter: false
  - dashboardUid: loki
    dashboardLabel: Loki
    panelId: 1
    panelTitle: Log items per second
    metricClassification: USE_errors
    higherIsBetter: false
  - dashboardUid: gatling-loki-logs
    dashboardLabel: Gatling Loki Logs
    panelId: 64
    panelTitle: Log items per second
    metricClassification: RED_errors
    higherIsBetter: false
